import Phaser from 'phaser';
import {Traveler} from '../entities/Traveler';
import {CompanionAI} from '../systems/CompanionAI';
import {WildlifeSystem} from '../systems/WildlifeSystem';
import {BiomeBackdrop,DepthLayers,landscape} from '../systems/Landscape';
import {HUD} from '../ui/HUD';
import {label} from '../ui/theme';
import {zones} from '../data/wildlife';
export class LevelScene extends Phaser.Scene{
 player!:Traveler;companion!:Traveler;wildlife!:WildlifeSystem;ai!:CompanionAI;hud!:HUD;backdrop!:BiomeBackdrop;layers!:DepthLayers;keys!:Record<string,Phaser.Input.Keyboard.Key>;binoculars=false;aim={x:820,y:450};idle=0;vibes=false;seen=new Set<number>();checkpoint=140;lastPhoto=-1000;noticeTimer?:Phaser.Time.TimerEvent;touchMove=0;
 constructor(){super('LevelScene');}
 create(){this.binoculars=false;this.idle=0;this.vibes=false;this.seen=new Set();this.checkpoint=140;this.lastPhoto=-1000;this.touchMove=0;landscape(this,44800,false);this.backdrop=new BiomeBackdrop(this);this.layers=new DepthLayers(this);this.physics.world.setBounds(0,0,44800,900);const ground=this.physics.add.staticGroup();const g=this.add.graphics().setVisible(false);
 const terrain=(x:number,y:number,w:number,h:number)=>{this.layers.terrain(x,y,w,h);const b=ground.create(x+w/2,y+h/2,'block') as Phaser.Physics.Arcade.Image;b.setDisplaySize(w,h).refreshBody().setVisible(false);g.fillStyle(0x6e624c);g.fillRect(x,y,w,h);g.fillStyle(0x3e6a4a);g.fillRect(x,y,w,12);g.fillStyle(0xb5aa6b);g.fillRect(x,y+12,w,5);for(let q=0;q<w;q+=39){g.fillStyle(q%2?0x867657:0x5c5545);g.fillRect(x+q,y+28+(q%43),18,8);}};
 let start=0;for(const gap of [7400,16800,27200,34400]){terrain(start,600,gap-start,300);terrain(gap-40,558,60,16);terrain(gap+35,552,80,16);start=gap+150;}terrain(start,600,44800-start,300);for(const x of [2600,10600,19600,28800,36400])terrain(x,500,130,18);
 this.player=new Traveler(this,140,'pablo');this.companion=new Traveler(this,65,'lujan');this.physics.add.collider(this.player,ground);this.physics.add.collider(this.companion,ground);this.ai=new CompanionAI();this.wildlife=new WildlifeSystem(this);this.hud=new HUD(this);this.keys=this.input.keyboard!.addKeys('A,D,LEFT,RIGHT,UP,DOWN,SPACE,B,F,E,TAB,ESC') as Record<string,Phaser.Input.Keyboard.Key>;this.input.keyboard!.addCapture(['SPACE','TAB','UP','DOWN']);this.cameras.main.setBounds(0,0,44800,720).startFollow(this.player,true,.09,.09,-170,90);
 for(const a of this.wildlife.animals){const x=a.data.x-300;label(this,x,529,a.data.bonus?'UNA ÚLTIMA MIRADA →':'MIRADOR DE FAUNA →',14,'#ffdda0');this.add.rectangle(x+8,580,8,40,0x72573d);}
 label(this,44320,499,'FIN DEL SENDERO\nE · celebrar el viaje',22,'#ffdda0');this.add.rectangle(44540,520,8,160,0x72573d);this.add.rectangle(44595,470,104,64,0xf2d394);label(this,44548,451,'JUNTOS\nAL SUR',17,'#081f35');
 this.input.on('pointermove',(p:Phaser.Input.Pointer)=>{this.aim.x=Phaser.Math.Clamp(p.x,20,1260);this.aim.y=Phaser.Math.Clamp(p.y,130,625);});
 if(!this.sys.game.device.os.desktop){const actions=[['←',60,()=>{this.touchMove=-1;}],['→',145,()=>{this.touchMove=1;}],['↑',240,()=>this.jump()],['B',930,()=>this.toggleBinoculars()],['F',1010,()=>this.photo()],['E',1090,()=>this.interact()],['Álbum',1190,()=>this.album()]] as const;for(const [text,x,fn] of actions){label(this,x,598,text,24).setOrigin(.5).setPadding(16).setBackgroundColor('#081f35').setScrollFactor(0).setDepth(80).setInteractive().on('pointerdown',fn).on('pointerup',()=>{this.touchMove=0;}).on('pointerout',()=>{this.touchMove=0;});}}
 this.say('Luján: Trajiste el mapa, ¿no?\nPablo: Sí. El zorro todavía no confirmó el itinerario.');
 }
 say(text:string){this.noticeTimer?.remove();this.hud.notice.setText(text).setVisible(true);this.noticeTimer=this.time.delayedCall(5200,()=>this.hud.notice.setVisible(false));}
 jump(){if(!this.hud.album.visible&&(this.player.body as Phaser.Physics.Arcade.Body).blocked.down&&!this.binoculars)this.player.setVelocityY(-470);}
 toggleBinoculars(){if(this.hud.album.visible)return;this.binoculars=!this.binoculars;this.wildlife.focus=0;this.hud.hint.setText(this.binoculars?'ENFOCAR: mouse / flechas · mantener 1,5 s · F fotografiar · B guardar':'A/D mover · ESPACIO saltar · B observar · F foto · E hablar · TAB álbum');}
 album(){this.hud.toggleAlbum(this.wildlife);if(this.hud.album.visible)this.physics.pause();else this.physics.resume();}
 photo(){if(!this.binoculars||this.time.now-this.lastPhoto<700)return;this.lastPhoto=this.time.now;this.player.pose('photo',420);const photo=this.wildlife.photo(this.player.x,{x:this.aim.x+this.cameras.main.scrollX,y:this.aim.y+this.cameras.main.scrollY});if(photo){this.cameras.main.flash(100,255,244,218);this.say(`FOTO · ${photo.a.data.name} · ${photo.score} puntos`);}else this.say('Buscá un animal dentro del círculo para sacar una foto.');}
 interact(){this.player.pose('interact',650);if(this.player.x>44000){if(this.wildlife.count===5)this.scene.start('EndingScene',{bonus:this.wildlife.found.has('bonus'),score:[...this.wildlife.photos.values()].reduce((a,b)=>a+b,0)});else this.say(`Luján: Nos faltan ${5-this.wildlife.count} especies. Volvamos a los miradores.`);}else this.say(this.wildlife.count===5?'Luján: Ya están las cinco. ¡Un zorro nos espera antes del final!':'Luján: En los miradores, B abre los binoculares.\nBuscá al animal con el mouse o las flechas y sostené el enfoque.');}
 update(time:number,delta:number){if(!this.player)return;const dt=Math.min(delta,50);const just=(k:string)=>Phaser.Input.Keyboard.JustDown(this.keys[k]);if(just('TAB')||(just('ESC')&&this.hud.album.visible))this.album();if(this.hud.album.visible)return;if(just('B'))this.toggleBinoculars();if(just('SPACE'))this.jump();if(just('E'))this.interact();
 let direction=(this.keys.D.isDown||(!this.binoculars&&this.keys.RIGHT.isDown)?1:0)-(this.keys.A.isDown||(!this.binoculars&&this.keys.LEFT.isDown)?1:0)+this.touchMove;this.player.walk(this.binoculars?0:direction*155,time);if(this.binoculars)this.player.pose('observe');this.ai.update(this.player,this.companion,time,this.cameras.main.scrollX);if(this.player.y>760){this.player.setPosition(this.checkpoint,450).setVelocity(0);this.say('Luján: Atajo descartado. Probemos saltando.');}if(this.companion.y>760)this.companion.setPosition(Math.max(20,this.player.x-100),420).setVelocity(0);if((this.player.body as Phaser.Physics.Arcade.Body).blocked.down)this.checkpoint=this.player.x;
 if(this.binoculars){this.aim.x=Phaser.Math.Clamp(this.aim.x+(Number(this.keys.RIGHT.isDown)-Number(this.keys.LEFT.isDown))*dt*.4,20,1260);this.aim.y=Phaser.Math.Clamp(this.aim.y+(Number(this.keys.DOWN.isDown)-Number(this.keys.UP.isDown))*dt*.4,130,625);}
 const aim=this.binoculars?{x:this.aim.x+this.cameras.main.scrollX,y:this.aim.y+this.cameras.main.scrollY}:null;this.wildlife.update(dt,this.player.x,aim,a=>{this.say(`AVISTAMIENTO · ${a.data.name}\n${this.wildlife.found.size}/5 · ${a.data.fact}`);});if(just('F'))this.photo();this.hud.aim.clear();if(this.binoculars){this.hud.aim.lineStyle(3,0xffdd93,.95).strokeCircle(this.aim.x,this.aim.y,65);this.hud.aim.lineBetween(this.aim.x-10,this.aim.y,this.aim.x+10,this.aim.y);this.hud.aim.lineBetween(this.aim.x,this.aim.y-10,this.aim.x,this.aim.y+10);this.hud.aim.fillStyle(0xffdd93).fillRect(this.aim.x-60,this.aim.y+76,120*this.wildlife.focus/1500,6);}
 this.backdrop.update(this.player.x);const zone=this.backdrop.zone;this.hud.update(this.wildlife,zones[zone]);if(!this.seen.has(zone)){this.seen.add(zone);if(zone>0)this.say(['','Pablo: El lago salió igual que en la foto.\nLuján: Falta que vos salgas enfocado.','Luján: El guanaco nos está evaluando.\nPablo: Espero que no pida referencias.','Pablo: ¿Escuchás ese golpeteo?\nLuján: El carpintero sí trajo herramientas.','Luján: Despacio. El huemul merece silencio.\nPablo: Mi mejor comentario hasta ahora.'][zone]);}
 const still=Math.abs(this.player.body!.velocity.x)<1&&Math.abs(this.player.body!.velocity.y)<1;this.idle=still?this.idle+dt:0;if(this.idle>=10000&&!this.vibes){this.vibes=true;this.say('♥ GOOD VIBES ONLY ♥\nNo es solo un destino… es con vos.');}if(!still)this.vibes=false;
 }
}


